version: '2'

services:
  discourse-app:
    container_name: discourse-app
    image: tiredofit/discourse:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.discourse-selfdesign-org.rule=Host(`discourse.example.com`)
      - traefik.http.services.discourse-selfdesign-org.loadbalancer.server.port=3000
    volumes:
      - ./logs:/app/log
      - ./uploads:/app/public/uploads
      - ./backups:/app/public/backups
    environment:
      - TIMEZONE=America/Vancouver
      - ZABBIX_HOSTNAME=discourse-app

      - DISCOURSE_DB_HOST=discourse-db
      - DISCOURSE_DB_PASSWORD=password
      - DISCOURSE_REDIS_HOST=discourse-redis
      - DISCOURSE_HOSTNAME=discourse.example.com
      - DISCOURSE_SMTP_ADDRESS=postfix-relay
      - DISCOURSE_SMTP_PORT='25'
      #- DISCOURSE_SMTP_USER_NAME=smtpuser
      #- DISCOURSE_SMTP_PASSWORD=password
      - DISCOURSE_DEVELOPER_EMAILS=hostmaster@your.domain
    restart: always
    networks:
      - proxy
      - services

  discourse-db:
    container_name: discourse-db
    image: tiredofit/postgres:latest
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - TIMEZONE=America/Vancouver
      - POSTGRES_DB=discourse
      - POSTGRES_USER=discourse
      - POSTGRES_PASSWORD=password
    networks:
      - services

  discourse-db-backup:
    image: tiredofit/db-backup
    container_name: discourse-db-backup
    links:
     - discourse-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - TIMEZONE=America/Vancouver
      - ZABBIX_HOSTNAME=discourse-db-backup
      - DB_HOST=discourse-db
      - DB_TYPE=postgres
      - DB_NAME=discourse
      - DB_USER=discourse
      - DB_PASS=password
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    networks:
      - services
    restart: always

  discourse-redis:
    image: tiredofit/redis:latest
    container_name: discourse-selfdesign-org-redis
    volumes:
      - ./redis:/var/lib/redis
    environment:
      - TIMEZONE=America/Vancouver
      - ZABBIX_HOSTNAME=discourse-redis
    networks:
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true


